### ISSUE TITLE
Misleading timestamp label in UI (Unix Seconds -> Unix Millis?)

### ISSUE THREAD

**Issue by s-rwe** [redpanda-data/console#923]
When choosing to show the raw timestamps in Messages view, the label to do this reads "Unix Seconds" which just seems misleading, since the actual values shown are not in seconds but milliseconds since Unix epoch.

![image](https://github.com/redpanda-data/console/assets/123059570/983d9752-f3b2-4d48-a45d-1fd59837392d)

It's quite a minor thing of course, since from the values it's generally apparent which unit is really behind. But still this should rather read "Unix Millis" or similar, to avoid unnecessary confusion.

I suppose the origin of this unit-mismatch comes from the unit-change introduced by https://github.com/redpanda-data/console/issues/184

**Comment by weeco** [comment]
Thanks @s-rwe for filing this issue and even doing the research how this may have been introduced. This should be a simple fix, do you want to tackle it as well?

**Comment by s-rwe** [comment]
@weeco - thanks, yeah simple enough fix I suppose. Submitted #924 accordingly (though I didn't try to really test or run anything based on the change).

**Comment by twmb** [comment]
I think the fix was merged? This will go out with the next major release -- closing the tracking ticket for now.

**Comment by s-rwe** [comment]
A small follow-up question, although that's more related to release process.

I've updated to latest release, running in docker container - from image `docker.redpanda.com/redpandadata/console:v2.3.8`

With that, the UI still looks as if the changes of #924 (which are included in tag v2.3.8 / 5190e51a) aren't really live, i.e. I still see the timestamp as "Seconds":

![image](https://github.com/redpanda-data/console/assets/123059570/77675565-7cb7-4a12-aeba-8582083a0e0c)

I double-checked that the container runs from the right image, cleaned browser storage, and also logged in anew from an anonymous tab to verify this is not just due to some issue on my end related to browser cache or similar.

@weeco Could there be something off / stale in the way the release is created...? At least I can't imagine where else this discrepancy would come from.

**Comment by weeco** [comment]
Only changes that are backported into the release-2.3 branch will make it to the v2.3.x Docker image. This has not been the case. You can use the following image if you want to test the latest version that was built against master: `redpandadata/console-unstable:master-e810c69`. We'll cut v2.4.x very soon.

**Comment by s-rwe** [comment]
Okay, thanks understood. That just makes the info shown in https://github.com/redpanda-data/console/releases/tag/v2.3.8 misleading, as it mentions that docker image / tag along with that specific commit.

Well it's not that I so desparately need this either - was more curious ;)
